version: "3.8"

services:
    composer:
        image: "composer:latest"
        user: 1000:1000
        volumes:
            - .:/app
        working_dir: /app
        command: install
    php:
        image: "php:7.3"
        user: 1000:1000
        ports:
            - 8000:8000
        volumes:
            - .:/app
        working_dir: /app
        command: php -S 0.0.0.0:8000 -t public

